name: Build JAR

on:
  push:
    branches: [ master, main ]
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'gradle/**'
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # Execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necessário para análise de mudanças
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Pull published Docker image
      run: |
        # Pull da imagem publicada
        docker pull axwayjbarros/aws-lambda-apim-sdk:1.0.0
        
    - name: Check if Release is Needed
      id: release_check
      run: |
        echo "🔍 Verificando se release é necessário..."
        ./scripts/check-release-needed.sh
        
        if [ -f .release_check ]; then
          source .release_check
          echo "📋 Resultado da análise:"
          echo "   Release necessário: $RELEASE_NEEDED"
          echo "   Arquivos relevantes: $RELEVANT_FILES"
          
          if [ "$RELEASE_NEEDED" = "true" ]; then
            echo "🔴 Release será criado!"
            echo "version_type=$VERSION_TYPE" >> $GITHUB_OUTPUT
            echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "release_needed=true" >> $GITHUB_OUTPUT
          else
            echo "🟢 Nenhum release necessário"
            echo "release_needed=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "⚠️  Arquivo .release_check não encontrado"
          echo "release_needed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Build JAR using published image
      run: |
        # Executar build do JAR usando a imagem publicada
        docker run --rm \
          -v "$(pwd):/workspace" \
          -v "$(pwd)/build:/workspace/build" \
          -v "$(pwd)/.gradle:/workspace/.gradle" \
          -w /workspace \
          axwayjbarros/aws-lambda-apim-sdk:1.0.0 \
          bash -c "
            echo '🔧 Configurando ambiente...'
            export JAVA_HOME=/opt/java/openjdk-11
            export PATH=\$JAVA_HOME/bin:\$PATH
            
            echo '📦 Verificando Java...'
            java -version
            
            echo '📦 Verificando Gradle...'
            gradle --version || echo 'Gradle não encontrado, instalando...'
            
            echo '🔨 Executando build...'
            gradle -Daxway.base=/opt/Axway clean build
            
            echo '📋 Verificando resultado...'
            ls -la build/libs/ || echo 'Diretório build/libs não encontrado'
          "
        
    - name: Test JAR
      run: |
        # Verificar se o JAR foi criado
        echo "🔍 Verificando JAR criado..."
        ls -la build/libs/aws-lambda-apim-sdk-*.jar || echo "❌ JAR não encontrado"
        
        # Verificar conteúdo do JAR
        echo "📋 Conteúdo do JAR:"
        jar -tf build/libs/aws-lambda-apim-sdk-*.jar | head -10 || echo "❌ Não foi possível verificar conteúdo"
        
        # Verificar tamanho do JAR
        echo "📏 Tamanho do JAR:"
        du -h build/libs/aws-lambda-apim-sdk-*.jar || echo "❌ Não foi possível verificar tamanho"
        
        # Verificar se o JAR contém as classes principais
        echo "🔍 Verificando classes principais..."
        jar -tf build/libs/aws-lambda-apim-sdk-*.jar | grep -E "(AWSLambdaFilter|AWSLambdaProcessor)" || echo "❌ Classes principais não encontradas"
        
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: aws-lambda-apim-sdk-jar
        path: build/libs/aws-lambda-apim-sdk-*.jar
        retention-days: 30
        
    - name: Create Tag and Release
      if: steps.release_check.outputs.release_needed == 'true' && github.event_name != 'pull_request' && contains(github.ref, 'master')
      run: |
        echo "🚀 Criando tag e release automaticamente..."
        
        # Configurar git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Obter informações da versão
        source .release_check
        NEW_VERSION="$NEW_VERSION"
        
        echo "📋 Criando tag: v$NEW_VERSION"
        
        # Criar tag
        git tag "v$NEW_VERSION"
        
        # Push da tag (isso acionará o workflow de release)
        git push origin "v$NEW_VERSION"
        
        echo "✅ Tag v$NEW_VERSION criada e enviada!"
        echo "🔄 Workflow de release será acionado automaticamente"
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const jarFiles = fs.readdirSync('build/libs').filter(file => file.endsWith('.jar'));
            const jarFile = jarFiles[0];
            const jarPath = path.join('build/libs', jarFile);
            const stats = fs.statSync(jarPath);
            const sizeInMB = (stats.size / (1024 * 1024)).toFixed(2);
            
            // Ler informações do release se disponível
            let releaseInfo = '';
            try {
              const fs = require('fs');
              if (fs.existsSync('.release_check')) {
                const releaseData = fs.readFileSync('.release_check', 'utf8');
                const lines = releaseData.split('\n');
                const releaseMap = {};
                lines.forEach(line => {
                  const [key, value] = line.split('=');
                  if (key && value) releaseMap[key] = value;
                });
                
                if (releaseMap.RELEASE_NEEDED === 'true' && releaseMap.NEW_VERSION) {
                  releaseInfo = `
                  
                  🔢 **Análise de Release:**
                  📊 **Release necessário:** ${releaseMap.RELEASE_NEEDED}
                  📈 **Nova versão:** ${releaseMap.NEW_VERSION}
                  📋 **Versão anterior:** ${releaseMap.OLD_VERSION}
                  🔍 **Tipo:** ${releaseMap.VERSION_TYPE}
                  📁 **Arquivos relevantes:** ${releaseMap.RELEVANT_FILES}`;
                } else {
                  releaseInfo = `
                  
                  🟢 **Análise de Release:**
                  📊 **Release necessário:** ${releaseMap.RELEASE_NEEDED || 'false'}
                  📋 **Motivo:** Nenhuma mudança relevante detectada`;
                }
              }
            } catch (e) {
              console.log('Não foi possível ler informações do release:', e.message);
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ Build concluído com sucesso!
              
              📦 **JAR criado:** ${jarFile}
              📏 **Tamanho:** ${sizeInMB} MB
              🔧 **Build com:** axwayjbarros/aws-lambda-apim-sdk:1.0.0${releaseInfo}
              
              O JAR está disponível como artifact para download.`
            });
          } catch (error) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `❌ Build falhou!
              
              Erro: ${error.message}
              
              Verifique os logs para mais detalhes.`
            });
          } 