name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Download JAR from previous workflow
      uses: actions/download-artifact@v4
      with:
        name: aws-lambda-apim-sdk-jar
        path: ./build/libs/
        
    - name: Generate changelog
      id: changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        git log --oneline $(git describe --tags --abbrev=0 HEAD^)..HEAD >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release
          
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ## Build Information
          
          This release was built using the Docker image `axwayjbarros/aws-lambda-apim-sdk:1.0.0` which contains:
          - Axway API Gateway 7.7.0.20240830
          - Java 11 OpenJDK
          - AWS SDK for Java 1.12.314
          - All necessary dependencies for building the filter
          
          ## Installation
          
          Download the JAR file from the assets below and follow the installation guide in the README.
          
          ## Usage
          
          This JAR contains the AWS Lambda integration for Axway API Gateway. 
          Follow the installation guide in the README for setup instructions.
        draft: false
        prerelease: false
        
    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libs/aws-lambda-apim-sdk-*.jar
        asset_name: aws-lambda-apim-sdk-${{ github.ref_name }}.jar
        asset_content_type: application/java-archive
        
    - name: Test JAR
      run: |
        # Verificar se o JAR foi baixado
        echo "🔍 Verificando JAR baixado..."
        ls -la build/libs/aws-lambda-apim-sdk-*.jar || echo "❌ JAR não encontrado"
        
        # Verificar conteúdo do JAR
        echo "📋 Conteúdo do JAR:"
        jar -tf build/libs/aws-lambda-apim-sdk-*.jar | head -10 || echo "❌ Não foi possível verificar conteúdo"
        
        # Verificar tamanho do JAR
        echo "📏 Tamanho do JAR:"
        du -h build/libs/aws-lambda-apim-sdk-*.jar || echo "❌ Não foi possível verificar tamanho"
        
        # Verificar se o JAR contém as classes principais
        echo "🔍 Verificando classes principais..."
        jar -tf build/libs/aws-lambda-apim-sdk-*.jar | grep -E "(AWSLambdaFilter|AWSLambdaProcessor)" || echo "❌ Classes principais não encontradas" 